Document K8 clusters in Platdorm docs (SAAS-916)
percona-platform/portal-doc pull request #22
Opened 2022-08-01 14:33 UTC by catalinaadam

2022-08-11 10:55 UTC, Nailya approved these changes

2022-08-22 15:35 UTC, zstefanyshyn submitted a review, later dismissed

2022-08-24 09:05 UTC, zstefanyshyn requested changes

2022-08-24 09:05 UTC, zstefanyshyn commented on docs/rel-notes/august-2022.md
> +Percona Platform now enables you to spin up a te,pKubernetes cluster, on demand. Use the **Launch a new cluster** option on the new **Free Kubernetes** tab to deploy a Kubernetes cluster with 3 nodes
a temporary Kubernetes cluster?

2022-08-24 13:14 UTC, zstefanyshyn approved these changes

2022-08-24 13:14 UTC, merged